from typing import Any

from fastapi import APIRouter

router = APIRouter(tags=["Integration"])


@router.post("/recommend")
def recommend(data: dict[str, Any]) -> dict[str, Any]:
    """
    Placeholder endpoint for the Reinforcement Learning module.
    """

    return {
        "success": True,
        "message": "Recommendation request received",
        "data": {
            "student_id": data.get("student_id"),
            "recommended_content": None,
            "difficulty": data.get("difficulty"),
            "next_action": "Will be generated by RL module",
        },
    }


@router.post("/attention")
def attention(data: dict[str, Any]) -> dict[str, Any]:
    """
    Receives attention score from the facial analysis module.
    """

    return {
        "success": True,
        "message": "Attention score received",
        "data": {
            "student_id": data.get("student_id"),
            "attention_score": data.get("attention_score"),
        },
    }