from typing import Any

from fastapi import APIRouter

from app.services.telemetry_service import (
    get_telemetry,
    reset_telemetry,
    update_telemetry,
)

router = APIRouter(tags=["Integration"])


@router.post("/recommend")
def recommend(data: dict[str, Any]) -> dict[str, Any]:
    return {
        "success": True,
        "message": "Recommendation request received",
        "data": {
            "student_id": data.get("student_id"),
            "recommended_content": None,
            "difficulty": data.get("difficulty"),
            "next_action": "Will be generated by RL module",
        },
    }


@router.post("/attention")
def attention(data: dict[str, Any]) -> dict[str, Any]:
    student_id = data.get("student_id")
    attention_score = data.get("attention_score")

    if student_id is not None and attention_score is not None:
        update_telemetry(
            student_id=int(student_id),
            attention_score=float(attention_score),
            yawning=bool(data.get("yawning", False)),
            looking_away=bool(data.get("looking_away", False)),
        )

    return {
        "success": True,
        "message": "Attention score received",
        "data": {
            "student_id": student_id,
            "attention_score": attention_score,
            "yawning": data.get("yawning", False),
            "looking_away": data.get("looking_away", False),
        },
    }


@router.get("/attention/{student_id}")
def get_attention(student_id: int) -> dict[str, Any]:
    telemetry = get_telemetry(student_id)

    return {
        "success": True,
        "message": "Latest attention telemetry fetched",
        "data": telemetry,
    }


@router.post("/attention/{student_id}/reset")
def reset_attention(student_id: int) -> dict[str, Any]:
    reset_telemetry(student_id)

    return {
        "success": True,
        "message": "Quiz telemetry reset",
        "data": get_telemetry(student_id),
    }